-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Protectors of the Endless", {
	[117052] = "yellow",
	[117227] = "yellow",
	[117309] = {"orange","red","yellow"},
	[117436] = {"blue","red"},
	[117975] = "orange",
	[117986] = "blue",
	[118077] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Protectors of the Endless", {
	[117052] = "info",
	[117309] = {"alert","info"},
	[117436] = "alert",
	[117986] = "info",
	[118077] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Tsulong", {
	[-6550] = "orange",
	[122752] = "orange",
	[122768] = "blue",
	[122777] = {"blue","red"},
	[122789] = "green",
	[122855] = "orange",
	[123011] = "red",
	["berserk"] = {"orange","red","yellow"},
	["embodied_terror"] = "yellow",
	["phases"] = {"green","yellow"},
	["unstable_sha"] = "red",
})

BigWigs:AddSounds("Tsulong", {
	[-6550] = "alarm",
	[122768] = "info",
	[122777] = "alert",
	[123011] = "alert",
	["berserk"] = "alarm",
	["phases"] = "alert",
	["unstable_sha"] = "alert",
})

BigWigs:AddColors("Lei Shi", {
	[123121] = {"blue","orange"},
	[123244] = "yellow",
	[123250] = {"green","red"},
	[123461] = {"green","red"},
	[123705] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["special"] = "yellow",
})

BigWigs:AddSounds("Lei Shi", {
	[123121] = "info",
	[123250] = "alarm",
	[123461] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Sha of Fear", {
	[-6700] = "red",
	[-6699] = {"orange","red"},
	[-6109] = "blue",
	[-6107] = "green",
	[118977] = "yellow",
	[119414] = "yellow",
	[119519] = "orange",
	[119888] = {"red","yellow"},
	[120268] = {"blue","green"},
	[120455] = "yellow",
	[120519] = {"blue","orange"},
	[120629] = {"blue","red"},
	[120669] = {"blue","orange","red"},
	[120672] = "yellow",
	[129147] = {"blue","orange"},
	[129378] = "green",
	["berserk"] = {"orange","red","yellow"},
	["swing"] = "green",
})

BigWigs:AddSounds("Sha of Fear", {
	[-6700] = "alarm",
	[-6109] = "long",
	[119414] = "long",
	[119519] = "alarm",
	[119888] = "alert",
	[120268] = "long",
	[120519] = "info",
	[120629] = "alert",
	[120669] = "info",
	[120672] = "alarm",
	[129378] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Imperial Vizier Zor'lok", {
	[122740] = {"blue","yellow"},
	[122761] = {"blue","red"},
	["attenuation"] = {"orange","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["force"] = {"orange","red"},
	["stages"] = "green",
})

BigWigs:AddSounds("Imperial Vizier Zor'lok", {
	["attenuation"] = {"alarm","alert"},
	["berserk"] = "alarm",
	["force"] = "long",
	["stages"] = "info",
})

BigWigs:AddColors("Blade Lord Ta'yak", {
	[-6350] = "green",
	[-6346] = {"blue","orange","yellow"},
	[123474] = {"blue","orange"},
	[125310] = "red",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Blade Lord Ta'yak", {
	[-6350] = "long",
	[-6346] = {"alarm","alert"},
	[123474] = "info",
	[125310] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Garalon", {
	[-6294] = "green",
	[122754] = "orange",
	[122774] = "red",
	[122835] = {"blue","red","yellow"},
	[123081] = {"blue","yellow"},
	[123120] = "blue",
	[123495] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Garalon", {
	[-6294] = {"info","long"},
	[122774] = "alarm",
	[122835] = {"alarm","info"},
	[123120] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Wind Lord Mel'jarak", {
	[-6554] = "yellow",
	[121881] = {"blue","red"},
	[121896] = {"blue","orange"},
	[122055] = "green",
	[122064] = "blue",
	[122125] = "blue",
	[122149] = "yellow",
	[122224] = "blue",
	[122406] = "red",
	[122409] = {"blue","orange"},
	[131830] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
	["mending"] = "blue",
	["recklessness"] = "yellow",
	["stages"] = "green",
})

BigWigs:AddSounds("Wind Lord Mel'jarak", {
	[121881] = "info",
	[121896] = {"alarm","info"},
	[122064] = "info",
	[122125] = "info",
	[122149] = "alert",
	[122224] = "info",
	[122406] = "alert",
	[122409] = "alarm",
	[131830] = "alarm",
	["berserk"] = "alarm",
	["mending"] = "alert",
	["recklessness"] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Amber-Shaper Un'sok", {
	[-6548] = {"blue","red"},
	[121949] = {"blue","orange"},
	[121995] = "yellow",
	[122408] = "orange",
	[122413] = {"blue","orange"},
	[122784] = {"blue","orange"},
	[123020] = "blue",
	[123060] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["explosion_by_other"] = "yellow",
	["explosion_casting_by_other"] = {"blue","red"},
	["explosion_casting_by_you"] = "blue",
	["stages"] = {"green","yellow"},
	["willpower"] = "blue",
})

BigWigs:AddSounds("Amber-Shaper Un'sok", {
	[-6548] = "alert",
	[121949] = "long",
	[122408] = "alarm",
	[122413] = "alarm",
	[122784] = "alarm",
	[123020] = "alarm",
	["berserk"] = "alarm",
	["explosion_casting_by_other"] = "alert",
	["explosion_casting_by_you"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Grand Empress Shek'zeer", {
	[-6325] = "yellow",
	[123788] = {"blue","yellow"},
	[123845] = {"blue","red"},
	[124077] = "orange",
	[124097] = "blue",
	[124849] = "red",
	[124862] = {"blue","red","yellow"},
	[125390] = {"blue","yellow"},
	[125826] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["eyes"] = {"blue","orange"},
	["phases"] = "green",
})

BigWigs:AddSounds("Grand Empress Shek'zeer", {
	[123788] = "long",
	[123845] = "info",
	[124077] = "long",
	[124097] = "info",
	[124849] = "alert",
	[124862] = {"alarm","alert"},
	[125390] = "info",
	["berserk"] = "alarm",
	["eyes"] = "info",
	["phases"] = "info",
})

BigWigs:AddColors("The Stone Guard", {
	[115852] = "cyan",
	[116006] = "cyan",
	[116036] = "cyan",
	[116057] = "cyan",
	[116529] = "orange",
	[130395] = {"blue","yellow"},
	[130774] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["energy"] = "red",
})

BigWigs:AddSounds("The Stone Guard", {
	[115852] = "alert",
	[116006] = "alert",
	[116036] = "alert",
	[116057] = "alert",
	[116529] = "info",
	[130395] = "warning",
	[130774] = "underyou",
	["berserk"] = "alarm",
	["energy"] = "long",
})

BigWigs:AddColors("Feng the Accursed", {
	[115817] = "orange",
	[115911] = {"blue","orange"},
	[116018] = "red",
	[116157] = "orange",
	[116364] = {"red","yellow"},
	[116417] = {"blue","orange"},
	[116711] = "red",
	[116784] = {"blue","orange"},
	[116793] = "blue",
	[118071] = "red",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
	["tank"] = {"blue","purple"},
})

BigWigs:AddSounds("Feng the Accursed", {
	[115817] = "info",
	[115911] = "info",
	[116018] = "alarm",
	[116364] = "alarm",
	[116417] = "warning",
	[116711] = "alarm",
	[116784] = "warning",
	[116793] = "underyou",
	[118071] = "alarm",
	["berserk"] = "alarm",
	["stages"] = "info",
	["tank"] = "info",
})

BigWigs:AddColors("Gara'jal the Spiritbinder", {
	[116174] = "yellow",
	[116272] = "orange",
	[117752] = "red",
	[122151] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Gara'jal the Spiritbinder", {
	[116272] = "alarm",
	[117752] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("The Spirit Kings", {
	[117697] = {"green","red"},
	[117708] = "orange",
	[117837] = "orange",
	[117910] = "yellow",
	[117961] = {"green","red"},
	[118047] = "orange",
	[118094] = "orange",
	[118122] = {"blue","red"},
	[118162] = "red",
	[118303] = "blue",
	[119521] = "orange",
	["berserk"] = {"orange","red"},
	["bosses"] = "cyan",
	["cowardice"] = {"blue","green","orange","yellow"},
})

BigWigs:AddSounds("The Spirit Kings", {
	[117697] = {"alert","info"},
	[117708] = "alarm",
	[117837] = "alert",
	[117910] = "long",
	[117961] = {"alert","info"},
	[118047] = "alarm",
	[118122] = "alarm",
	[118162] = "alert",
	[118303] = "info",
	[119521] = "alarm",
	["berserk"] = "alarm",
	["bosses"] = "info",
})

BigWigs:AddColors("Elegon", {
	[-6186] = "red",
	[117878] = "blue",
	[119360] = "yellow",
	["adds"] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["floor"] = "blue",
	["stages"] = "green",
})

BigWigs:AddSounds("Elegon", {
	[-6186] = "alert",
	[117878] = "info",
	["berserk"] = "alarm",
	["floor"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Will of the Emperor", {
	[-5670] = {"red","yellow"},
	[116525] = "blue",
	[116829] = {"blue","yellow"},
	["arc"] = "orange",
	["berserk"] = {"orange","red"},
	["bosses"] = "yellow",
	["combo"] = "orange",
	["courage"] = "yellow",
	["rage"] = "yellow",
	["strength"] = "yellow",
})

BigWigs:AddSounds("Will of the Emperor", {
	[-5670] = "alarm",
	[116525] = "info",
	[116829] = "info",
	["berserk"] = "alarm",
	["combo"] = "long",
})

BigWigs:AddColors("Sha of Anger", {
	[119488] = "yellow",
	[119610] = "blue",
	[119622] = "blue",
	[119626] = {"blue","red"},
})

BigWigs:AddSounds("Sha of Anger", {
	[119610] = "underyou",
	[119622] = "warning",
})

BigWigs:AddColors("Salyis's Warband", {
	[121600] = "orange",
	[121787] = "red",
	["adds"] = "cyan",
})

BigWigs:AddSounds("Salyis's Warband", {
	[121600] = "long",
	[121787] = "alarm",
	["adds"] = "info",
})

BigWigs:AddColors("Nalak", {
	[136338] = "red",
	[136339] = "blue",
	[136340] = {"blue","yellow"},
})

BigWigs:AddSounds("Nalak", {
	[136338] = "alarm",
	[136339] = "alert",
	[136340] = {"alert","info"},
})

BigWigs:AddColors("Oondasta", {
	[137457] = "yellow",
	[137504] = {"blue","orange"},
	[137505] = "red",
})

BigWigs:AddSounds("Oondasta", {
	[137457] = "long",
	[137504] = "info",
	[137505] = "alert",
})

BigWigs:AddColors("Ordos", {
	[144688] = "orange",
	[144689] = {"blue","orange"},
	[144692] = {"blue","yellow"},
	[144695] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Ordos", {
	[144689] = "alert",
	[144692] = {"alarm","info"},
	[144695] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Immerseus", {
	[143020] = "cyan",
	[143295] = "blue",
	[143309] = "red",
	[143436] = {"blue","orange"},
	[143469] = "cyan",
	[143574] = "yellow",
	[143579] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Immerseus", {
	[143295] = "info",
	[143309] = "long",
	[143436] = {"alarm","warning"},
	[143574] = "alert",
	[143579] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("The Fallen Protectors", {
	[-7959] = {"blue","orange"},
	[-7958] = "orange",
	[143007] = "red",
	[143019] = "blue",
	[143027] = "yellow",
	[143292] = {"blue","yellow"},
	[143330] = "orange",
	[143423] = "blue",
	[143446] = "orange",
	[143491] = "yellow",
	[143497] = "green",
	[143564] = "blue",
	[143840] = {"blue","red"},
	[143958] = "blue",
	[144367] = "blue",
	[144396] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["defile_you"] = "blue",
	["inferno_self"] = {"blue","orange"},
	["intermission"] = {"cyan","red"},
})

BigWigs:AddSounds("The Fallen Protectors", {
	[-7958] = "alarm",
	[143007] = "alarm",
	[143019] = "info",
	[143292] = "long",
	[143330] = "warning",
	[143423] = "warning",
	[143446] = "alarm",
	[143497] = "warning",
	[143564] = "info",
	[143840] = {"alert","info"},
	[143958] = "info",
	[144367] = "info",
	[144396] = "alarm",
	["berserk"] = "alarm",
	["defile_you"] = "info",
	["inferno_self"] = "warning",
	["intermission"] = {"alert","info"},
})

BigWigs:AddColors("Norushen", {
	[-8220] = {"blue","cyan"},
	[-8218] = "yellow",
	[144482] = "yellow",
	[144514] = "orange",
	[144628] = "yellow",
	[144649] = "orange",
	[145132] = "yellow",
	[145226] = "red",
	[146124] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["big_adds"] = {"orange","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Norushen", {
	[-8220] = "warning",
	[144482] = "info",
	[144514] = "warning",
	[144628] = "info",
	[144649] = "warning",
	[145226] = "long",
	[146124] = "info",
	["berserk"] = "alarm",
	["big_adds"] = {"alarm","alert"},
	["stages"] = {"info","warning"},
})

BigWigs:AddColors("Sha of Pride", {
	[-8349] = "cyan",
	[-8270] = {"blue","yellow"},
	[-8262] = "orange",
	[-8258] = "blue",
	[-8257] = "blue",
	[144351] = "red",
	[144358] = {"blue","red"},
	[144400] = "yellow",
	[144563] = {"blue","cyan"},
	[144800] = "red",
	[144832] = "cyan",
	[145215] = {"blue","yellow"},
	[146595] = {"cyan","green"},
	[146817] = "blue",
	[147207] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Sha of Pride", {
	[-8349] = "info",
	[-8262] = "alert",
	[-8258] = "warning",
	[-8257] = "alarm",
	[144351] = "alarm",
	[144358] = "warning",
	[144400] = "info",
	[144832] = "info",
	[146595] = "long",
	[146817] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Galakras", {
	[-8489] = "orange",
	[-8443] = "orange",
	[146757] = "red",
	[146765] = "blue",
	[146769] = "orange",
	[146899] = {"blue","orange"},
	[147068] = {"blue","red","yellow"},
	[147328] = "orange",
	[147705] = "blue",
	["adds"] = "yellow",
	["demolisher"] = "yellow",
	["drakes"] = "yellow",
	["stages"] = {"blue","cyan"},
	["towers"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Galakras", {
	[-8489] = "warning",
	[-8443] = "alert",
	[146757] = "warning",
	[146769] = "alert",
	[146899] = "alarm",
	[147068] = "warning",
	[147705] = "info",
	["adds"] = "info",
	["drakes"] = "info",
	["stages"] = "warning",
	["towers"] = "long",
})

BigWigs:AddColors("Iron Juggernaut", {
	[-8190] = {"blue","red"},
	[-8183] = "orange",
	[-8181] = "yellow",
	[-8179] = {"blue","yellow"},
	[144459] = {"blue","red"},
	[144467] = {"blue","yellow"},
	[144485] = "yellow",
	[144498] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Iron Juggernaut", {
	[-8190] = "warning",
	[-8179] = "info",
	[144485] = "alert",
	[144498] = "info",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Kor'kron Dark Shaman", {
	[-8132] = {"blue","green"},
	[-8124] = "cyan",
	[143973] = "yellow",
	[143990] = {"blue","red"},
	[144005] = {"blue","orange"},
	[144070] = "cyan",
	[144215] = {"blue","yellow"},
	[144302] = "cyan",
	[144328] = "red",
	[144330] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Kor'kron Dark Shaman", {
	[-8132] = "alarm",
	[-8124] = "info",
	[143973] = "info",
	[143990] = "alert",
	[144005] = {"alert","info"},
	[144215] = "warning",
	[144302] = "info",
	[144328] = "long",
	[144330] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("General Nazgrim", {
	[-7947] = {"blue","yellow"},
	[-7933] = {"blue","yellow"},
	[-7920] = "cyan",
	[-7915] = "green",
	[143431] = "red",
	[143474] = "yellow",
	[143475] = {"blue","green"},
	[143494] = {"blue","yellow"},
	[143502] = "red",
	[143503] = "red",
	[143536] = "yellow",
	[143638] = {"blue","orange"},
	[143716] = {"blue","orange"},
	[143872] = {"blue","orange"},
	["arcane_shock"] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["chain_heal"] = "blue",
})

BigWigs:AddSounds("General Nazgrim", {
	[-7947] = "alarm",
	[-7933] = "info",
	[-7920] = {"info","long"},
	[-7915] = "alert",
	[143431] = "alarm",
	[143475] = "warning",
	[143494] = "info",
	[143502] = "warning",
	[143503] = "warning",
	[143536] = "alert",
	[143638] = "info",
	[143716] = "alarm",
	[143872] = "alarm",
	["arcane_shock"] = "alert",
	["berserk"] = "alarm",
	["chain_heal"] = "alert",
})

BigWigs:AddColors("Malkorok", {
	[142826] = "yellow",
	[142842] = "red",
	[142851] = "orange",
	[142879] = "cyan",
	[142913] = {"blue","orange"},
	[142986] = "orange",
	[142990] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Malkorok", {
	[142842] = "warning",
	[142851] = "info",
	[142879] = "long",
	[142913] = "alert",
	[142986] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Spoils of Pandaria", {
	[142694] = "yellow",
	[142947] = "orange",
	[145288] = "red",
	[145461] = "orange",
	[145692] = {"blue","orange"},
	[145715] = "blue",
	[145747] = "blue",
	[145786] = {"orange","yellow"},
	[145987] = {"green","red"},
	[146217] = "blue",
	[146222] = "yellow",
	[146257] = "blue",
	[146815] = "red",
	["berserk"] = "green",
	["crates"] = {"red","yellow"},
})

BigWigs:AddSounds("Spoils of Pandaria", {
	[142947] = {"alarm","warning"},
	[145288] = "alert",
	[145461] = "alarm",
	[145692] = "alarm",
	[145715] = "info",
	[145747] = "info",
	[145786] = "alarm",
	[145987] = "warning",
	[146217] = "info",
	[146222] = "long",
	[146257] = "info",
	[146815] = "alert",
	["crates"] = "long",
})

BigWigs:AddColors("Thok the Bloodthirsty", {
	[-7981] = {"cyan","yellow"},
	[-7980] = {"blue","green","orange"},
	[-7963] = "yellow",
	[143766] = {"blue","yellow"},
	[143767] = {"blue","yellow"},
	[143773] = {"blue","yellow"},
	[143777] = {"blue","yellow"},
	[143780] = {"blue","yellow"},
	[143783] = "blue",
	[145974] = {"blue","orange"},
	[146589] = {"blue","green","yellow"},
	[148145] = "red",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Thok the Bloodthirsty", {
	[-7981] = "long",
	[-7980] = "alarm",
	[143766] = "warning",
	[143767] = "warning",
	[143773] = "warning",
	[143780] = "warning",
	[143783] = "info",
	[145974] = "alert",
	[146589] = {"alert","warning"},
	[148145] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Siegecrafter Blackfuse", {
	[-8408] = "red",
	[-8212] = {"blue","orange"},
	[-8208] = "blue",
	[-8207] = "green",
	[-8202] = {"cyan","green"},
	[-8199] = "yellow",
	[-8195] = {"blue","green"},
	[143385] = {"blue","yellow"},
	[143639] = "orange",
	[143856] = "blue",
	[144208] = "yellow",
	[144466] = "red",
	[145365] = "yellow",
	[145444] = "orange",
	[146479] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Siegecrafter Blackfuse", {
	[-8212] = "info",
	[-8208] = "info",
	[-8202] = "warning",
	[-8199] = "long",
	[-8195] = "info",
	[143385] = "info",
	[143856] = "info",
	[144208] = "alert",
	[144466] = "long",
	[145365] = "long",
	[146479] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Paragons of the Klaxxi", {
	[-8073] = {"blue","red"},
	[-8065] = "blue",
	[-8055] = {"blue","yellow"},
	[-8034] = {"blue","cyan"},
	[-8008] = {"blue","orange"},
	[-8003] = "cyan",
	[142564] = {"blue","red"},
	[142671] = {"blue","red"},
	[142803] = "blue",
	[142931] = {"blue","yellow"},
	[143243] = "orange",
	[143280] = "red",
	[143337] = "yellow",
	[143339] = {"green","orange","yellow"},
	[143576] = "blue",
	[143701] = {"blue","orange"},
	[143735] = "blue",
	[143759] = "yellow",
	[143939] = {"blue","orange"},
	[143974] = {"blue","orange"},
	[148589] = {"blue","red"},
	[148677] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Paragons of the Klaxxi", {
	[-8073] = "warning",
	[-8065] = "info",
	[-8055] = "info",
	[-8034] = {"alert","long"},
	[-8008] = "alarm",
	[142564] = "warning",
	[142671] = "warning",
	[142803] = "info",
	[143243] = "long",
	[143280] = "warning",
	[143337] = "alert",
	[143339] = {"info","warning"},
	[143576] = "info",
	[143701] = "info",
	[143735] = "info",
	[143939] = "alarm",
	[143974] = "alarm",
	[148589] = "warning",
	[148677] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Garrosh Hellscream", {
	[-8305] = "cyan",
	[-8298] = "yellow",
	[-8294] = "orange",
	[-8292] = "yellow",
	[144616] = "red",
	[144758] = {"blue","orange"},
	[144821] = "yellow",
	[144945] = {"blue","green","yellow"},
	[144969] = "yellow",
	[144985] = "red",
	[145065] = "orange",
	[145183] = {"blue","yellow"},
	[147209] = {"blue","orange"},
	[147235] = "blue",
	[147665] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["bombardment"] = "yellow",
	["chain_heal"] = "blue",
	["clump_check"] = "red",
	["manifest_rage"] = "red",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Garrosh Hellscream", {
	[-8294] = "alert",
	[144758] = "alarm",
	[144945] = {"long","warning"},
	[144985] = "long",
	[145065] = "alert",
	[145183] = "warning",
	[147209] = "alarm",
	[147235] = "alert",
	[147665] = "warning",
	["berserk"] = "alarm",
	["chain_heal"] = "alert",
	["clump_check"] = "long",
	["manifest_rage"] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("Jin'rokh the Breaker", {
	[-7741] = {"blue","green"},
	[137162] = "yellow",
	[137175] = {"blue","red"},
	[137313] = "red",
	[138006] = "blue",
	[138349] = {"blue","orange"},
	[138732] = {"green","red"},
	[139467] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Jin'rokh the Breaker", {
	[-7741] = "alarm",
	[137175] = "warning",
	[137313] = "long",
	[138006] = "info",
	[138349] = "alert",
	[138732] = {"info","long"},
	[139467] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Horridon", {
	[-7868] = "blue",
	[-7125] = {"blue","red"},
	[-7120] = {"blue","orange"},
	[-7119] = "red",
	[-7109] = "red",
	[-7092] = "green",
	[-7090] = {"green","red"},
	[-7086] = "cyan",
	[-7080] = {"blue","yellow"},
	[-7078] = {"blue","orange"},
	[136490] = "blue",
	[136573] = "blue",
	[136646] = "blue",
	[136723] = "blue",
	[136741] = "orange",
	[136821] = "red",
	[137240] = "green",
	[137458] = "orange",
	["adds"] = "cyan",
	["berserk"] = {"orange","red","yellow"},
	["chain_lightning"] = "blue",
	["fireball"] = "blue",
	["venom_bolt_volley"] = {"blue","red"},
})

BigWigs:AddSounds("Horridon", {
	[-7868] = "info",
	[-7125] = "alarm",
	[-7119] = "alarm",
	[-7109] = "alarm",
	[-7090] = "long",
	[-7080] = "warning",
	[136490] = "info",
	[136573] = "info",
	[136646] = "info",
	[136723] = "info",
	[136741] = "long",
	[136821] = "long",
	["adds"] = "info",
	["berserk"] = "alarm",
	["chain_lightning"] = "alert",
	["fireball"] = "alert",
	["venom_bolt_volley"] = {"alarm","alert"},
})

BigWigs:AddColors("Council of Elders", {
	[-7062] = "blue",
	[-7054] = {"blue","orange","red","yellow"},
	[136442] = {"cyan","orange","red","yellow"},
	[136857] = {"blue","yellow"},
	[136878] = "yellow",
	[136894] = "orange",
	[136990] = {"blue","green"},
	[136992] = {"blue","orange"},
	[137085] = "blue",
	[137122] = "blue",
	[137203] = "yellow",
	[137350] = {"blue","orange"},
	[137650] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["priestess_adds"] = "red",
})

BigWigs:AddSounds("Council of Elders", {
	[-7062] = "info",
	[-7054] = {"info","warning"},
	[136442] = {"alert","long"},
	[136857] = "info",
	[136894] = "alert",
	[136990] = "info",
	[136992] = "alert",
	[137085] = "info",
	[137122] = "info",
	[137350] = "alert",
	[137650] = "info",
	["berserk"] = "alarm",
	["priestess_adds"] = "alarm",
})

BigWigs:AddColors("Tortos", {
	[-7134] = "green",
	[133939] = "red",
	[134920] = "red",
	[135251] = "yellow",
	[136010] = "red",
	[136294] = "orange",
	[137633] = "blue",
	["bats"] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["kick"] = "yellow",
})

BigWigs:AddSounds("Tortos", {
	[-7134] = "info",
	[133939] = "long",
	[134920] = "alert",
	[135251] = "warning",
	[136010] = "alarm",
	[137633] = {"alarm","info"},
	["bats"] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Megaera", {
	[139458] = {"green","red","yellow"},
	[139822] = {"blue","red"},
	[139843] = {"blue","orange"},
	[139866] = {"blue","orange"},
	[139909] = "blue",
	[140138] = "orange",
	[140179] = {"blue","orange"},
	["breaths"] = {"blue","yellow"},
})

BigWigs:AddSounds("Megaera", {
	[139458] = "long",
	[139822] = {"alert","info"},
	[139843] = "warning",
	[139866] = "info",
	[139909] = "info",
	[140138] = "alarm",
	["breaths"] = "info",
})

BigWigs:AddColors("Ji-Kun", {
	[-7360] = "blue",
	[134366] = {"blue","orange"},
	[134370] = "red",
	[134380] = "red",
	[137528] = "green",
	[138923] = "yellow",
	[140092] = {"blue","yellow"},
	[140741] = "green",
	["berserk"] = {"orange","red","yellow"},
	["nest"] = {"orange","yellow"},
})

BigWigs:AddSounds("Ji-Kun", {
	[-7360] = "info",
	[134366] = "info",
	[134370] = "long",
	[134380] = "warning",
	[137528] = "info",
	["berserk"] = "alarm",
	["nest"] = "alert",
})

BigWigs:AddColors("Durumu the Forgotten", {
	[-6905] = {"blue","yellow"},
	[-6891] = {"blue","cyan"},
	[-6889] = "orange",
	[-6882] = "yellow",
	[133597] = "blue",
	[133767] = {"blue","yellow"},
	[133768] = {"blue","orange"},
	[133798] = {"blue","green","red"},
	[134626] = "orange",
	[140502] = "blue",
	["adds"] = {"green","orange","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["initial_life_drain"] = {"blue","orange"},
})

BigWigs:AddSounds("Durumu the Forgotten", {
	[-6905] = "long",
	[-6891] = "warning",
	[133597] = "info",
	[133767] = "info",
	[133768] = "alarm",
	[133798] = "alert",
	[134626] = "alarm",
	[140502] = "info",
	["adds"] = {"info","warning"},
	["berserk"] = "alarm",
	["initial_life_drain"] = "long",
})

BigWigs:AddColors("Primordius", {
	[-7830] = "blue",
	[-6969] = "yellow",
	[-6960] = "blue",
	[136037] = "yellow",
	[136050] = {"blue","yellow"},
	[136216] = "orange",
	[136218] = {"green","red"},
	[136228] = {"blue","green","orange","red"},
	[136245] = "yellow",
	[136246] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Primordius", {
	[-7830] = "info",
	[-6960] = "info",
	[136050] = "warning",
	[136218] = {"alert","long"},
	[136228] = {"alarm","alert","long"},
	["berserk"] = "alarm",
})

BigWigs:AddColors("Dark Animus", {
	[-7770] = {"blue","orange"},
	[136954] = "red",
	[138485] = {"blue","green","orange"},
	[138609] = {"blue","red"},
	[138644] = "cyan",
	[138691] = {"blue","orange"},
	[138729] = "red",
	[138763] = {"blue","yellow"},
	[138780] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["matterswap"] = "blue",
})

BigWigs:AddSounds("Dark Animus", {
	[-7770] = "info",
	[136954] = "alert",
	[138485] = {"alarm","info"},
	[138609] = {"alarm","info"},
	[138644] = {"info","warning"},
	[138691] = "alarm",
	[138729] = "long",
	[138763] = "long",
	["berserk"] = "alarm",
	["matterswap"] = "info",
})

BigWigs:AddColors("Iron Qon", {
	[-6917] = "orange",
	[-6914] = "yellow",
	[-6877] = {"green","yellow"},
	[-6871] = "red",
	[77333] = "yellow",
	[134691] = {"blue","green"},
	[134926] = {"blue","orange"},
	[136192] = {"blue","orange"},
	[136193] = {"blue","green"},
	[136520] = "blue",
	[137221] = "red",
	[137668] = "blue",
	[137669] = "blue",
	[139180] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["molten_energy"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Iron Qon", {
	[-6917] = "alarm",
	[-6871] = "warning",
	[134691] = "warning",
	[134926] = "alarm",
	[136193] = "alert",
	[136520] = "info",
	[137668] = "info",
	[137669] = "info",
	["berserk"] = "alarm",
	["molten_energy"] = "long",
})

BigWigs:AddColors("Twin Consorts", {
	[-7649] = "green",
	[-7643] = "yellow",
	[-7638] = "blue",
	[-7634] = {"blue","yellow"},
	[-7631] = "orange",
	[137408] = {"blue","orange"},
	[137440] = "blue",
	[137491] = {"green","red"},
	[137531] = "orange",
	[138300] = "green",
	[138306] = "green",
	[138318] = "green",
	[138855] = "green",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Twin Consorts", {
	[-7643] = "warning",
	[-7638] = "info",
	[-7634] = "info",
	[-7631] = "alarm",
	[137408] = "info",
	[137440] = "info",
	[137491] = "alert",
	[137531] = "alarm",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Lei Shen", {
	[134912] = "blue",
	[135095] = "yellow",
	[135150] = {"blue","yellow"},
	[135695] = {"blue","green"},
	[135991] = {"blue","red"},
	[136295] = {"blue","green","orange"},
	[136366] = "red",
	[136478] = "red",
	[136543] = "yellow",
	[136850] = {"blue","orange","red"},
	[136889] = "red",
	[136914] = {"blue","red"},
	[139011] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = {"cyan","green","yellow"},
})

BigWigs:AddSounds("Lei Shen", {
	[134912] = "warning",
	[135095] = "alert",
	[135150] = "info",
	[135695] = "info",
	[135991] = "warning",
	[136295] = "alarm",
	[136366] = "long",
	[136478] = "warning",
	[136850] = {"alert","info","warning"},
	[136889] = "long",
	[136914] = "warning",
	[139011] = "alert",
	["berserk"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Ra-den", {
	[138288] = {"blue","yellow"},
	[138297] = "blue",
	[138333] = "yellow",
	[138334] = {"blue","cyan"},
	[138339] = "yellow",
	[138372] = "blue",
	["balls"] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["corruptedballs"] = "red",
	["stages"] = "cyan",
	["unstablevitajumptarget"] = "blue",
	["worm"] = "orange",
})

BigWigs:AddSounds("Ra-den", {
	[138297] = "info",
	[138372] = "info",
	["balls"] = "warning",
	["berserk"] = "alarm",
	["corruptedballs"] = "alarm",
	["stages"] = "info",
	["unstablevitajumptarget"] = {"info","long"},
})

BigWigs:AddColors("Throne of Thunder Trash", {
	[139322] = {"blue","orange"},
	[139899] = "orange",
	[139900] = {"blue","orange"},
	[140296] = "yellow",
	[140673] = "yellow",
})

BigWigs:AddSounds("Throne of Thunder Trash", {
	[139322] = "alert",
	[139899] = "long",
	[139900] = "alert",
	[140296] = "info",
	[140673] = "long",
})
