sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "j+0gwpVQNeB8iqIWqDHFjYZ1i4mBIBmBYUghOsvzTx6Llc7nMODf2bVU7k3RwDj09Ua2sppDsr7gYDqOurfNINX63J+YEuObq138oaEa6znCDGxQClf1dnAxFbTxT3eoIO84kGfI+FwuKmt9xULcbkk+7iuglZJazV09NCb83jbXgmlGPE7RYz3Grww0AwwvhXX26k00mX2fWX8Cx71OVAqJk/s4xoL2/9PqOL3qPOngNbYPy7lhkVK8PaBvOxKDFkIW7p/4rrFbLSRT1kYzGtmSoPbUxzLX6aTGtSIqgA2gmkZvhLLa3ao4SvO/b1WxeRyZiVOvgnwYbXfnVrPf2afprW4l2TafxKCO1Fx58e88xD3vh5gDD95LPiCaIU5iDk+A6GxhQHsQdjmF6RBI6ZDEhcf/nyXqiRI8H0HhEXFGo0qLdSFzM+IAuQRILgI7r84Nvp1RM2DO+BAjBpq1RRUTYn+Q+Cm2FXCirLsMx/FbdwfmEMhNx2y6p/o/8nL8TItMkOiKKTivTOjQbIScA5P76z5sxIvyaPkRaZ42lnKNDLLV3KDyka8nveShqgwOGPc6bs7vEnwu+4TCCRlCg7qGM2DiUk7EG1+dWgnU7J0QjJkWH81mWe81BfgtRjpxJVq/7G8lpT0MPTBgZHuIbKByoyITyCBCMMBEJTvUzPM="
  - secure: "hE0Qfz/6L9satF4HdF01leFPvjkQU03A69lFwWNEpEQn/OYWkFYqgYXewPqPZJ72lbUG06wYRVJPgJpm1iiXUf/syJU/F3rtCBT4kZQov4UAlgREjXZ/0jHXNT4TvEyDBDAbyO/SVZZ3IAvwIPIx5lrzjI3vl9ePn3EF2/KuThLmXJ9rIAWjjISlHe/Jz7cdOE8MTLPRwT2VKTt/8hgiJNz0pbuiHnpmPq6JVGb0Gr1ejRshALUYwLsyWTGhyed9dzfy/DrET6S06gmivZdFb1/KMtjpZ/kXgDZtPZJ4CeA2q7hy7HMSDHgfEdCUXhMqRqTCqg5hrjEvGgF2Q0QdbBF0f4ja1ObjgtIPLacbr09YUKf6yoRSqoQnkv80K/3wrtEkYHV1TxMKb8Kw38wPlGmwJRquOKInO6jk/TydlpYWo4QLrzi44vSNRt85RIBlZTvu5d0l73/iF+nTShQTayBCbMrJ3wAZ0osYO+58OkhU+M/pc4caDJpT7XAMEfpRWS2wfy0vX4j1Qh64wgLmpAivw7LSQnygqDvKp29ManisEhVPb4fdwhswuHkIbtH3HuS5NupaUNQ625VmxQX4nQw8cJ3E++070V3AWgOsIBkC1DmcD+RpJ6GkpuS+VTElLd1odb/xr9tQWjdcHZfybTwV9SN5r2OR7iJSiMxdWyI="
  - secure: "F2Lffsbag/Rinfq3qUtJygJyrJZGeQMbRssNuHbnYS3560IQAcl2a4YXitwckbySLaKlcwxRAECT71Iz0JgGdHwUUI7eW9DOdiOvTIBF8ZhxUgLkC1GTDpKBmrgx++OdYevWFuYNdJuyVybn4U/Lz2mzZ8KED/fFIqmbvy9+CIyrYD/07fvUPXBqBr3l85KgmZEU/z9851DwmaFwJLMTewT+kT3xEPJUYDBcsxqNgtNeNvRs6CkGIdxZPjDqNDXG66OhUeDMakZRfkp1/7sYnN+T4Jc15sN6KPVQooOtD8iAX2iirb0wQcYs6dnw8nf7vXYECaJnKxi5z49xnLwvglEiGcKe0Pl+khtiyhucWESQ2jOfxVVqRSlHtBKX2wZgZw2eQDdC3uUuzBsHQLyTSZWjhRXZZuJ/6BE6a6e0M5x1Y9IwLDq+wgwgN7frqKJvoUbcApM7afuvHCNWbdJT830ZJ2QGpkl5XAQW3uil+zO1D29nnKm9tBTNkJSD7Z56+ACTE8D5UJzmi4f9a+fjJGM0+D39BXjspjgQqk+Q3Wy4OLsQajvyPnZJnUrR1SElKNPrWBYifUIL7pQga1Q3eLFLhvoREqphKDzBWJxryuWmMimcgOES7CSOniJe0HthDmreBSgEfmyoakJKdZEm4JKmIab5TjtQkrsB+z66n7Y="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
