sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "kSmYb33QpU8WXrrvFUeIoHm5FNY7G2X1lW2IvB0s3BwCbrquNGis5qrJp/b3AxwmOgy3y7NKh2331eXdKOpprLF/UyKR8CbgREkhM8QK5DbdheQAnd/+dS7hskXgdUsED6NFe0vqsPtikKn68oEo3lwUe2LXuJXtUPPznTazeBlNhPdXpxu2ag8YTGyZu7WIFZQKxx6zMBqUJfHYKXlUyP2pb3UH5DMyKGx4oK68D57TRwfxp7ZL2ja0WeMrydec0muSd7wyerPwW5vY0GlCbxprPkNfSrC7AYPj4Zbo4Ne0YSt8SMTytJGaDp25bUVBTn+9n4hdfVK99qrmUZ6mkReK4poxbBT5X264F8QuEnWCPCVHLDafxwp1Oy25dbEyilYvM7cyYDVpU81fjkleJPt5GBmObOoggrZvVnse6A14Ct5kBtTiJ3RgcACCzmJFzOAxkRaXkKiBf3oXuhUJwpJaPbJXDjoZDDgE4krm8bkzCq+fvI+j1dXTLDJUf3muzWsfsXtYzajOd3nvA360eRQEqbKJcDTLF3MvMQQnjAgi6YpfigEvArtW5S2hI2uHS/RGl+8tlYvdaPgppgIDcNkdXacdtmnmQ1T17CuXq0lgwzHK6CBSBlsvr0tmSmuc3We8UH4HUNl/6IXYojZLlroz55XVarbc8yY60Bl4Zhw="
  - secure: "hE0Qfz/6L9satF4HdF01leFPvjkQU03A69lFwWNEpEQn/OYWkFYqgYXewPqPZJ72lbUG06wYRVJPgJpm1iiXUf/syJU/F3rtCBT4kZQov4UAlgREjXZ/0jHXNT4TvEyDBDAbyO/SVZZ3IAvwIPIx5lrzjI3vl9ePn3EF2/KuThLmXJ9rIAWjjISlHe/Jz7cdOE8MTLPRwT2VKTt/8hgiJNz0pbuiHnpmPq6JVGb0Gr1ejRshALUYwLsyWTGhyed9dzfy/DrET6S06gmivZdFb1/KMtjpZ/kXgDZtPZJ4CeA2q7hy7HMSDHgfEdCUXhMqRqTCqg5hrjEvGgF2Q0QdbBF0f4ja1ObjgtIPLacbr09YUKf6yoRSqoQnkv80K/3wrtEkYHV1TxMKb8Kw38wPlGmwJRquOKInO6jk/TydlpYWo4QLrzi44vSNRt85RIBlZTvu5d0l73/iF+nTShQTayBCbMrJ3wAZ0osYO+58OkhU+M/pc4caDJpT7XAMEfpRWS2wfy0vX4j1Qh64wgLmpAivw7LSQnygqDvKp29ManisEhVPb4fdwhswuHkIbtH3HuS5NupaUNQ625VmxQX4nQw8cJ3E++070V3AWgOsIBkC1DmcD+RpJ6GkpuS+VTElLd1odb/xr9tQWjdcHZfybTwV9SN5r2OR7iJSiMxdWyI="
  - secure: "F2Lffsbag/Rinfq3qUtJygJyrJZGeQMbRssNuHbnYS3560IQAcl2a4YXitwckbySLaKlcwxRAECT71Iz0JgGdHwUUI7eW9DOdiOvTIBF8ZhxUgLkC1GTDpKBmrgx++OdYevWFuYNdJuyVybn4U/Lz2mzZ8KED/fFIqmbvy9+CIyrYD/07fvUPXBqBr3l85KgmZEU/z9851DwmaFwJLMTewT+kT3xEPJUYDBcsxqNgtNeNvRs6CkGIdxZPjDqNDXG66OhUeDMakZRfkp1/7sYnN+T4Jc15sN6KPVQooOtD8iAX2iirb0wQcYs6dnw8nf7vXYECaJnKxi5z49xnLwvglEiGcKe0Pl+khtiyhucWESQ2jOfxVVqRSlHtBKX2wZgZw2eQDdC3uUuzBsHQLyTSZWjhRXZZuJ/6BE6a6e0M5x1Y9IwLDq+wgwgN7frqKJvoUbcApM7afuvHCNWbdJT830ZJ2QGpkl5XAQW3uil+zO1D29nnKm9tBTNkJSD7Z56+ACTE8D5UJzmi4f9a+fjJGM0+D39BXjspjgQqk+Q3Wy4OLsQajvyPnZJnUrR1SElKNPrWBYifUIL7pQga1Q3eLFLhvoREqphKDzBWJxryuWmMimcgOES7CSOniJe0HthDmreBSgEfmyoakJKdZEm4JKmIab5TjtQkrsB+z66n7Y="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
